#! /usr/bin/env bash

# -------------------------------- Config --------------------------------

DLL_NAME="DevZH.UI.SimpleSample"

# ------------------------------- Functions ------------------------------

main_loop() {
    HERE=$(dirname $(readlink -f "${0}"))
    if ! [ -z $VER ]; then echo "AppImage auto-mounted at $HERE"; fi
    export LD_LIBRARY_PATH=$HERE/lib
    export HERE=$HERE
    export VER=$VER
    check_for_dotnet
}

check_for_dotnet() {
    LOC="$(which dotnet)"
    if [ -z "$LOC" ]; then
        echo ".NET runtime not detected, attempting new install..."
        $HERE/install/dotnet-installer.sh && start_app
    else
        if ! [ -z $VER ]; then
            echo ".NET runtime detected at $LOC, installer not required.";
        fi
        start_app
    fi
}

start_app() {
    dotnet $HERE/bin/$DLL_NAME.dll
    exit 0
}

# --------------------------------- Init ---------------------------------

if [ "$1" == "--appimg-v" ] || [ "$1" == "--appimg-verbose" ]; then
    VER="true";
fi
    export VER=$VER

main_loop
