#!/bin/bash -eux -y update

# Get appimagetool
mkdir -p /usr/share
cd /usr/share
curl -L -o appimagetool https://github.com/probonopd/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod a+x appimagetool
./appimagetool --appimage-extract
rm -f appimagetool
mv squashfs-root appimagetool
ln -s /usr/share/appimagetool/AppRun /usr/local/bin/appimagetool

# Get NET_Pkg Source
cd /tmp
git clone -b develop --single-branch https://github.com/phil-harmoniq/NET_Pkg --depth 1
mkdir -p /tmp/NET_Pkg/usr/share
cp -r /usr/share/appimagetool /tmp/NET_Pkg/usr/share
ln -s /tmp/NET_Pkg/usr/share/appimagetool/AppRun /tmp/NET_Pkg/usr/bin/appimagetool

# Run source build
chmod a+x build.sh
mkdir -p /netpkg-build
./build.sh . --docker-build
