#!/bin/bash -eux -y update

# Get appimagetool
curl -L -o /usr/local/bin/appimagetool https://github.com/probonopd/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod a+x /usr/local/bin/appimagetool

# Get NET_Pkg Source
cd /tmp
git clone https://github.com/phil-harmoniq/Net_Pkg

# Run source build
cd NET_Pkg
chmod a+x build.sh
mkdir -p /netpkg-build
./build.sh /netpkg-build --keep

